// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_login
 */
export type BodyLogin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * TokenResponse
 *
 * JWT Token 响应模型
 */
export type TokenResponse = {
    /**
     * Access Token
     *
     * 访问令牌
     */
    access_token: string;
    /**
     * Token Type
     *
     * 令牌类型
     */
    token_type?: string;
};

/**
 * UserListResponse
 *
 * 用户列表响应模型
 */
export type UserListResponse = {
    /**
     * Total
     *
     * 总数
     */
    total: number;
    /**
     * Users
     *
     * 用户列表
     */
    users: Array<UserResponse>;
};

/**
 * UserRegister
 *
 * 用户注册请求模型（仅限公开注册使用，不包含敏感字段）
 */
export type UserRegister = {
    /**
     * Username
     *
     * 用户名
     */
    username: string;
    /**
     * Email
     *
     * 邮箱
     */
    email: string;
    /**
     * Password
     *
     * 密码
     */
    password: string;
    /**
     * Full Name
     *
     * 全名
     */
    full_name?: string | null;
    /**
     * Bio
     *
     * 用户简介
     */
    bio?: string | null;
    /**
     * Avatar
     *
     * 用户头像 URL
     */
    avatar?: string | null;
};

/**
 * UserResponse
 *
 * 用户响应模型（不包含密码）
 */
export type UserResponse = {
    /**
     * Username
     *
     * 用户名
     */
    username: string;
    /**
     * Email
     *
     * 邮箱
     */
    email: string;
    /**
     * Is Active
     *
     * 是否激活
     */
    is_active: boolean;
    /**
     * 用户角色
     */
    role?: UserRole;
    /**
     * Full Name
     *
     * 全名
     */
    full_name?: string | null;
    /**
     * Bio
     *
     * 用户简介
     */
    bio?: string | null;
    /**
     * Avatar
     *
     * 用户头像 URL
     */
    avatar?: string | null;
    /**
     * Id
     *
     * 用户 ID
     */
    id: string;
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string;
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string;
    /**
     * Last Login
     *
     * 最后登录时间
     */
    last_login?: string | null;
};

/**
 * UserRole
 */
export type UserRole = 'user' | 'admin' | 'superadmin';

/**
 * UserUpdate
 *
 * 更新用户的请求模型（所有字段可选）
 */
export type UserUpdate = {
    /**
     * Username
     *
     * 用户名
     */
    username?: string | null;
    /**
     * Email
     *
     * 邮箱
     */
    email?: string | null;
    /**
     * Password
     *
     * 密码
     */
    password?: string | null;
    /**
     * Is Active
     *
     * 是否激活
     */
    is_active?: boolean | null;
    /**
     * 用户角色
     */
    role?: UserRole | null;
    /**
     * Full Name
     *
     * 全名
     */
    full_name?: string | null;
    /**
     * Bio
     *
     * 用户简介
     */
    bio?: string | null;
    /**
     * Avatar
     *
     * 用户头像 URL
     */
    avatar?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ReadRootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/users/register';
};

export type RegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * Successful Response
     */
    201: UserResponse;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type LoginData = {
    body: BodyLogin;
    path?: never;
    query?: never;
    url: '/users/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type DeleteCurrentUserAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type DeleteCurrentUserAccountResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCurrentUserAccountResponse = DeleteCurrentUserAccountResponses[keyof DeleteCurrentUserAccountResponses];

export type GetCurrentUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetCurrentUserInfoResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetCurrentUserInfoResponse = GetCurrentUserInfoResponses[keyof GetCurrentUserInfoResponses];

export type UpdateCurrentUserInfoData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UpdateCurrentUserInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCurrentUserInfoError = UpdateCurrentUserInfoErrors[keyof UpdateCurrentUserInfoErrors];

export type UpdateCurrentUserInfoResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UpdateCurrentUserInfoResponse = UpdateCurrentUserInfoResponses[keyof UpdateCurrentUserInfoResponses];

export type GetUsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Is Active
         */
        is_active?: boolean | null;
    };
    url: '/users/';
};

export type GetUsersListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersListError = GetUsersListErrors[keyof GetUsersListErrors];

export type GetUsersListResponses = {
    /**
     * Successful Response
     */
    200: UserListResponse;
};

export type GetUsersListResponse = GetUsersListResponses[keyof GetUsersListResponses];

export type DeleteUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type DeleteUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserByIdError = DeleteUserByIdErrors[keyof DeleteUserByIdErrors];

export type DeleteUserByIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserByIdResponse = DeleteUserByIdResponses[keyof DeleteUserByIdResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type UpdateUserByIdData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type UpdateUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserByIdError = UpdateUserByIdErrors[keyof UpdateUserByIdErrors];

export type UpdateUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UpdateUserByIdResponse = UpdateUserByIdResponses[keyof UpdateUserByIdResponses];
