"""Add Posts model

Revision ID: 3cd0c20d5ad6
Revises: 142a5adf705f
Create Date: 2025-12-29 01:49:55.020168

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3cd0c20d5ad6"
down_revision: Union[str, Sequence[str], None] = "142a5adf705f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
