"""Add excerpt and is_featured to Category

Revision ID: 52716b81b3bd
Revises: 733305de1f34
Create Date: 2026-01-27 09:38:44.485312

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401 - SQLModel 类型支持（如 AutoString）
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52716b81b3bd"
down_revision: Union[str, Sequence[str], None] = "733305de1f34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts_category",
        sa.Column(
            "excerpt",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
            server_default="",
        ),
    )
    op.add_column(
        "posts_category",
        sa.Column(
            "is_featured", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts_category", "is_featured")
    op.drop_column("posts_category", "excerpt")
    # ### end Alembic commands ###
