"""add_use_server_rendering_field_to_posts

Revision ID: 5e7200478855
Revises: b679abbe21c0
Create Date: 2026-01-12 04:04:59.587502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 类型支持（如 AutoString）


# revision identifiers, used by Alembic.
revision: str = '5e7200478855'
down_revision: Union[str, Sequence[str], None] = 'b679abbe21c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts_post', sa.Column('use_server_rendering', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts_post', 'use_server_rendering')
    # ### end Alembic commands ###
