"""feat: enhance analytics with bot detection and device info

Revision ID: 61700b9a81c4
Revises: b782d471d884
Create Date: 2026-01-28 16:06:14.919992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 - SQLModel 类型支持（如 AutoString）


# revision identifiers, used by Alembic.
revision: str = '61700b9a81c4'
down_revision: Union[str, Sequence[str], None] = 'b782d471d884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('referrer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visitor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('browser_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('os_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_event_pkey'))
    )
    op.create_index(op.f('analytics_event_browser_family_idx'), 'analytics_event', ['browser_family'], unique=False)
    op.create_index(op.f('analytics_event_device_family_idx'), 'analytics_event', ['device_family'], unique=False)
    op.create_index(op.f('analytics_event_event_type_idx'), 'analytics_event', ['event_type'], unique=False)
    op.create_index(op.f('analytics_event_is_bot_idx'), 'analytics_event', ['is_bot'], unique=False)
    op.create_index(op.f('analytics_event_os_family_idx'), 'analytics_event', ['os_family'], unique=False)
    op.create_index(op.f('analytics_event_page_path_idx'), 'analytics_event', ['page_path'], unique=False)
    op.create_index(op.f('analytics_event_post_id_idx'), 'analytics_event', ['post_id'], unique=False)
    op.create_index(op.f('analytics_event_referrer_idx'), 'analytics_event', ['referrer'], unique=False)
    op.create_index(op.f('analytics_event_session_id_idx'), 'analytics_event', ['session_id'], unique=False)
    op.create_index(op.f('analytics_event_user_id_idx'), 'analytics_event', ['user_id'], unique=False)
    op.create_index(op.f('analytics_event_visitor_id_idx'), 'analytics_event', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('analytics_event_visitor_id_idx'), table_name='analytics_event')
    op.drop_index(op.f('analytics_event_user_id_idx'), table_name='analytics_event')
    op.drop_index(op.f('analytics_event_session_id_idx'), table_name='analytics_event')
    op.drop_index(op.f('analytics_event_referrer_idx'), table_name='analytics_event')
    op.drop_index(op.f('analytics_event_post_id_idx'), table_name='analytics_event')
    op.drop_index(op.f('analytics_event_page_path_idx'), table_name='analytics_event')
    op.drop_index(op.f('analytics_event_os_family_idx'), table_name='analytics_event')
    op.drop_index(op.f('analytics_event_is_bot_idx'), table_name='analytics_event')
    op.drop_index(op.f('analytics_event_event_type_idx'), table_name='analytics_event')
    op.drop_index(op.f('analytics_event_device_family_idx'), table_name='analytics_event')
    op.drop_index(op.f('analytics_event_browser_family_idx'), table_name='analytics_event')
    op.drop_table('analytics_event')
    # ### end Alembic commands ###
