"""add_content_ast_field_to_posts

Revision ID: 72e2441e6137
Revises: 5e7200478855
Create Date: 2026-01-16 05:47:22.844304

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401 - SQLModel 类型支持（如 AutoString）
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "72e2441e6137"
down_revision: Union[str, Sequence[str], None] = "5e7200478855"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts_post",
        sa.Column(
            "content_ast", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###

    # 添加 GIN 索引（用于 JSONB 查询优化）
    op.create_index(
        "idx_posts_content_ast", "posts_post", ["content_ast"], postgresql_using="gin"
    )

    # 添加字段注释
    op.execute(
        "COMMENT ON COLUMN posts_post.content_ast IS 'AST 结构化内容（JSONB），用于高性能渲染'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # 回滚时先删除索引，再删除字段
    op.drop_index("idx_posts_content_ast", table_name="posts_post")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts_post", "content_ast")
    # ### end Alembic commands ###
