"""Add cover_media to Category

Revision ID: 733305de1f34
Revises: fdfd2915e1fd
Create Date: 2026-01-26 12:21:51.277344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 - SQLModel 类型支持（如 AutoString）


# revision identifiers, used by Alembic.
revision: str = '733305de1f34'
down_revision: Union[str, Sequence[str], None] = 'fdfd2915e1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts_category', sa.Column('cover_media_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('posts_category_cover_media_id_fkey'), 'posts_category', 'media_files', ['cover_media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('posts_category_cover_media_id_fkey'), 'posts_category', type_='foreignkey')
    op.drop_column('posts_category', 'cover_media_id')
    # ### end Alembic commands ###
