"""Add post_sort_order to Category

Revision ID: 992a2681f846
Revises: dfbaf0720606
Create Date: 2026-02-05 04:41:30.174889

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401 - SQLModel 类型支持（如 AutoString）
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "992a2681f846"
down_revision: Union[str, Sequence[str], None] = "dfbaf0720606"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 手动创建 Enum 类型
    post_sort_enum = sa.Enum(
        "published_at_desc",
        "published_at_asc",
        "title_asc",
        "title_desc",
        name="postsortorder",
    )
    post_sort_enum.create(op.get_bind())

    op.add_column(
        "posts_category",
        sa.Column(
            "post_sort_order",
            post_sort_enum,
            server_default="published_at_desc",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("posts_post_source_path_idx"), "posts_post", ["source_path"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("posts_post_source_path_idx"), table_name="posts_post")
    op.drop_column("posts_category", "post_sort_order")

    # 手动删除 Enum 类型
    sa.Enum(name="postsortorder").drop(op.get_bind())
    # ### end Alembic commands ###
