"""apply_naming_convention_to_constraints

Revision ID: ad030ca670fc
Revises: d297b19322ca
Create Date: 2025-12-30 02:12:40.442230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 类型支持（如 AutoString）


# revision identifiers, used by Alembic.
revision: str = 'ad030ca670fc'
down_revision: Union[str, Sequence[str], None] = 'd297b19322ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_files_file_path'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_usage'), table_name='media_files')
    op.create_index(op.f('media_files_file_path_idx'), 'media_files', ['file_path'], unique=True)
    op.create_index(op.f('media_files_usage_idx'), 'media_files', ['usage'], unique=False)
    op.drop_index(op.f('ix_posts_category_post_type'), table_name='posts_category')
    op.drop_index(op.f('ix_posts_category_slug'), table_name='posts_category')
    op.create_index(op.f('posts_category_post_type_idx'), 'posts_category', ['post_type'], unique=False)
    op.create_index(op.f('posts_category_slug_idx'), 'posts_category', ['slug'], unique=False)
    op.drop_index(op.f('ix_posts_post_post_type'), table_name='posts_post')
    op.drop_index(op.f('ix_posts_post_slug'), table_name='posts_post')
    op.drop_index(op.f('ix_posts_post_status'), table_name='posts_post')
    op.create_index(op.f('posts_post_post_type_idx'), 'posts_post', ['post_type'], unique=False)
    op.create_index(op.f('posts_post_slug_idx'), 'posts_post', ['slug'], unique=True)
    op.create_index(op.f('posts_post_status_idx'), 'posts_post', ['status'], unique=False)
    op.drop_index(op.f('ix_posts_post_version_post_id'), table_name='posts_post_version')
    op.create_index(op.f('posts_post_version_post_id_idx'), 'posts_post_version', ['post_id'], unique=False)
    op.drop_index(op.f('ix_posts_tag_slug'), table_name='posts_tag')
    op.create_index(op.f('posts_tag_slug_idx'), 'posts_tag', ['slug'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_index(op.f('users_username_idx'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('users_username_idx'), table_name='users')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('posts_tag_slug_idx'), table_name='posts_tag')
    op.create_index(op.f('ix_posts_tag_slug'), 'posts_tag', ['slug'], unique=True)
    op.drop_index(op.f('posts_post_version_post_id_idx'), table_name='posts_post_version')
    op.create_index(op.f('ix_posts_post_version_post_id'), 'posts_post_version', ['post_id'], unique=False)
    op.drop_index(op.f('posts_post_status_idx'), table_name='posts_post')
    op.drop_index(op.f('posts_post_slug_idx'), table_name='posts_post')
    op.drop_index(op.f('posts_post_post_type_idx'), table_name='posts_post')
    op.create_index(op.f('ix_posts_post_status'), 'posts_post', ['status'], unique=False)
    op.create_index(op.f('ix_posts_post_slug'), 'posts_post', ['slug'], unique=True)
    op.create_index(op.f('ix_posts_post_post_type'), 'posts_post', ['post_type'], unique=False)
    op.drop_index(op.f('posts_category_slug_idx'), table_name='posts_category')
    op.drop_index(op.f('posts_category_post_type_idx'), table_name='posts_category')
    op.create_index(op.f('ix_posts_category_slug'), 'posts_category', ['slug'], unique=False)
    op.create_index(op.f('ix_posts_category_post_type'), 'posts_category', ['post_type'], unique=False)
    op.drop_index(op.f('media_files_usage_idx'), table_name='media_files')
    op.drop_index(op.f('media_files_file_path_idx'), table_name='media_files')
    op.create_index(op.f('ix_media_files_usage'), 'media_files', ['usage'], unique=False)
    op.create_index(op.f('ix_media_files_file_path'), 'media_files', ['file_path'], unique=True)
    # ### end Alembic commands ###
