"""Ensure Post is_featured column

Revision ID: b782d471d884
Revises: 52716b81b3bd
Create Date: 2026-01-27 09:54:19.288303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 - SQLModel 类型支持（如 AutoString）


# revision identifiers, used by Alembic.
revision: str = 'b782d471d884'
down_revision: Union[str, Sequence[str], None] = '52716b81b3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
