"""add_analytics_geo_and_duration

Revision ID: c599e7e41a25
Revises: 61700b9a81c4
Create Date: 2026-01-28 10:42:31.352264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 - SQLModel 类型支持（如 AutoString）


# revision identifiers, used by Alembic.
revision: str = 'c599e7e41a25'
down_revision: Union[str, Sequence[str], None] = '61700b9a81c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_event', sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('analytics_event', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('analytics_event', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('analytics_event', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('analytics_event', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('analytics_event', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('analytics_event', sa.Column('duration', sa.Integer(), nullable=True))
    op.create_index(op.f('analytics_event_city_idx'), 'analytics_event', ['city'], unique=False)
    op.create_index(op.f('analytics_event_country_idx'), 'analytics_event', ['country'], unique=False)
    op.create_index(op.f('analytics_event_ip_address_idx'), 'analytics_event', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('analytics_event_ip_address_idx'), table_name='analytics_event')
    op.drop_index(op.f('analytics_event_country_idx'), table_name='analytics_event')
    op.drop_index(op.f('analytics_event_city_idx'), table_name='analytics_event')
    op.drop_column('analytics_event', 'duration')
    op.drop_column('analytics_event', 'longitude')
    op.drop_column('analytics_event', 'latitude')
    op.drop_column('analytics_event', 'region')
    op.drop_column('analytics_event', 'city')
    op.drop_column('analytics_event', 'country')
    op.drop_column('analytics_event', 'ip_address')
    # ### end Alembic commands ###
