"""add content_hash to media_files

Revision ID: cfef905e4e34
Revises: 72e2441e6137
Create Date: 2026-01-18 12:38:11.097832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 - SQLModel 类型支持（如 AutoString）
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfef905e4e34'
down_revision: Union[str, Sequence[str], None] = '72e2441e6137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.create_index(op.f('media_files_content_hash_idx'), 'media_files', ['content_hash'], unique=False)
    op.alter_column('posts_post', 'content_ast',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='AST 结构化内容（JSONB），用于高性能渲染',
               existing_nullable=True)
    op.drop_index(op.f('idx_posts_content_ast'), table_name='posts_post', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_posts_content_ast'), 'posts_post', ['content_ast'], unique=False, postgresql_using='gin')
    op.alter_column('posts_post', 'content_ast',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='AST 结构化内容（JSONB），用于高性能渲染',
               existing_nullable=True)
    op.drop_index(op.f('media_files_content_hash_idx'), table_name='media_files')
    op.drop_column('media_files', 'content_hash')
    # ### end Alembic commands ###
