"""Add Posts model

Revision ID: d297b19322ca
Revises: 3cd0c20d5ad6
Create Date: 2025-12-29 01:53:26.974678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel 类型支持（如 AutoString）


# revision identifiers, used by Alembic.
revision: str = 'd297b19322ca'
down_revision: Union[str, Sequence[str], None] = '3cd0c20d5ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_tag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_posts_tag_slug'), 'posts_tag', ['slug'], unique=True)
    op.create_table('posts_category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon_id', sa.Uuid(), nullable=True),
    sa.Column('icon_preset', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('post_type', sa.Enum('ARTICLE', 'IDEA', name='posttype'), nullable=False),
    sa.ForeignKeyConstraint(['icon_id'], ['media_files.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['posts_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'post_type', name='uq_category_slug_post_type')
    )
    op.create_index(op.f('ix_posts_category_post_type'), 'posts_category', ['post_type'], unique=False)
    op.create_index(op.f('ix_posts_category_slug'), 'posts_category', ['slug'], unique=False)
    op.create_table('posts_post',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('post_type', sa.Enum('ARTICLE', 'IDEA', name='posttype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('content_mdx', sa.TEXT(), nullable=True),
    sa.Column('content_html', sa.TEXT(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='poststatus'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('allow_comments', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('bookmark_count', sa.Integer(), nullable=False),
    sa.Column('reading_time', sa.Integer(), nullable=False),
    sa.Column('toc', sa.JSON(), nullable=True),
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('meta_keywords', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('git_hash', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('cover_media_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['posts_category.id'], ),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_post_post_type'), 'posts_post', ['post_type'], unique=False)
    op.create_index(op.f('ix_posts_post_slug'), 'posts_post', ['slug'], unique=True)
    op.create_index(op.f('ix_posts_post_status'), 'posts_post', ['status'], unique=False)
    op.create_table('posts_post_tag_link',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts_post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['posts_tag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_table('posts_post_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('content_mdx', sa.TEXT(), nullable=True),
    sa.Column('git_hash', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('commit_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_post_version_post_id'), 'posts_post_version', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_post_version_post_id'), table_name='posts_post_version')
    op.drop_table('posts_post_version')
    op.drop_table('posts_post_tag_link')
    op.drop_index(op.f('ix_posts_post_status'), table_name='posts_post')
    op.drop_index(op.f('ix_posts_post_slug'), table_name='posts_post')
    op.drop_index(op.f('ix_posts_post_post_type'), table_name='posts_post')
    op.drop_table('posts_post')
    op.drop_index(op.f('ix_posts_category_slug'), table_name='posts_category')
    op.drop_index(op.f('ix_posts_category_post_type'), table_name='posts_category')
    op.drop_table('posts_category')
    op.drop_index(op.f('ix_posts_tag_slug'), table_name='posts_tag')
    op.drop_table('posts_tag')
    # ### end Alembic commands ###
