"""add_region_and_isp_to_analytics_event

Revision ID: dfbaf0720606
Revises: c599e7e41a25
Create Date: 2026-01-30 16:12:03.654764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 - SQLModel 类型支持（如 AutoString）


# revision identifiers, used by Alembic.
revision: str = 'dfbaf0720606'
down_revision: Union[str, Sequence[str], None] = 'c599e7e41a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_event', sa.Column('isp', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('analytics_event_isp_idx'), 'analytics_event', ['isp'], unique=False)
    op.create_index(op.f('analytics_event_region_idx'), 'analytics_event', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('analytics_event_region_idx'), table_name='analytics_event')
    op.drop_index(op.f('analytics_event_isp_idx'), table_name='analytics_event')
    op.drop_column('analytics_event', 'isp')
    # ### end Alembic commands ###
