"""添加是否开启jsx或者tsx的选项

Revision ID: f4ca5113a4c0
Revises: ad030ca670fc
Create Date: 2026-01-11 11:02:31.999496

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4ca5113a4c0"
down_revision: Union[str, Sequence[str], None] = "ad030ca670fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 步骤1: 添加可空字段
    op.add_column("posts_post", sa.Column("enable_jsx", sa.Boolean(), nullable=True))

    # 步骤2: 给现有数据设置默认值 False
    op.execute("UPDATE posts_post SET enable_jsx = false WHERE enable_jsx IS NULL")

    # 步骤3: 改为不可空
    op.alter_column("posts_post", "enable_jsx", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts_post", "enable_jsx")
    # ### end Alembic commands ###
