"""remove_content_html_field

Revision ID: fdfd2915e1fd
Revises: cfef905e4e34
Create Date: 2026-01-23 03:57:42.602287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 - SQLModel 类型支持（如 AutoString）


# revision identifiers, used by Alembic.
revision: str = 'fdfd2915e1fd'
down_revision: Union[str, Sequence[str], None] = 'cfef905e4e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts_post', 'content_html')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts_post', sa.Column('content_html', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
